export const blogCategories = [
    "learning_tips",
    "study_guide",
    "exam_preparation",
    "eps_topik",
    "topik",
    "mock_test",
    "grammar_lessons",
    "vocabulary_building",
    "speaking_practice",
    "writing_practice",
    "listening_practice",
    "reading_practice",

    "success_story",
    "student_experience",
    "worker_experience",
    "life_in_korea",
    "culture_and_customs",
    "daily_life_in_korea",
    "workplace_life",
    "salary_and_benefits",
    "overtime_and_leave",

    "safety_guidelines",
    "factory_safety",
    "construction_safety",
    "health_and_medical",
    "accident_prevention",
    "workers_rights",
    "legal_information",
    "immigration_updates",

    "language_explanation",
    "common_mistakes",
    "bangla_to_korean",
    "korean_to_bangla",
    "pronunciation_tips",

    "resources",
    "pdf_books",
    "grammar_books",
    "self_study_materials",
    "practice_materials",

    "technology_updates",
    "app_features",
    "offline_learning",
    "ai_learning",

    "motivation",
    "career_guidance",
    "goal_setting",
    "productivity",

    "announcements",
    "updates",
    "maintenance_notice"
];