export const themeVocabularies = [
    "daily_life",
    "family",
    "friends",
    "food",
    "shopping",
    "housing",
    "transport",
    "health",
    "weather",
    "time_date",
    "hobbies",
    "emotions",
    "clothing",

    "workplace",
    "factory",
    "construction",
    "manufacturing",
    "safety",
    "tools",
    "machines",
    "instructions",
    "warnings",
    "permissions",
    "schedule",
    "salary",
    "overtime",
    "leave",
    "rules",

    "conversation",
    "question_answer",
    "commands",
    "requests",
    "suggestions",
    "apology",
    "agreement",
    "disagreement",
    "polite_speech",
    "honorifics",
    "formal",
    "informal",

    "travel",
    "directions",
    "airport",
    "immigration",
    "hotel",
    "restaurant",
    "public_service",
    "bank",
    "post_office",
    "police",
    "emergency",

    "education",
    "classroom",
    "exam",
    "study",
    "language_learning",
    "grammar",
    "vocabulary",
    "reading",
    "writing",
    "listening",
    "speaking",

    "medical",
    "hospital",
    "medicine",
    "injury",
    "accident",
    "first_aid",
    "fire_safety",
    "protective_equipment",
    "danger",
    "warning_signs",

    "numbers",
    "counting",
    "money",
    "measurement",
    "weight",
    "length",
    "quantity",
    "price",
    "percentage",
    "time_management",

    "technology",
    "mobile",
    "internet",
    "computer",
    "applications",
    "devices",
    "repair",
    "electricity",

    "nature",
    "animals",
    "plants",
    "environment",
    "pollution",
    "natural_disaster",
    "weather_alert",

    "movement",
    "action",
    "change",
    "state",
    "process",
    "cause_effect",
    "permission_prohibition",

    "culture",
    "tradition",
    "festival",
    "customs",
    "respect",
    "behavior",
    "social_rules"
]

